In [3]:
import numpy as np
import pandas as pd

In [11]:
n1 = np.array([[(111,112,113),(114,115,116)],
              [(211,212,213),(214,215,216)],
              [(311,312,313),(314,315,316)]])
print(n1)

[[[111 112 113]
  [114 115 116]]

 [[211 212 213]
  [214 215 216]]

 [[311 312 313]
  [314 315 316]]]


In [14]:
n1.shape

(3, 2, 3)

In [20]:
n2 = np.array([0,1,2,3,4])

print(n2)

[0 1 2 3 4]


In [22]:
n2

array([0, 1, 2, 3, 4])

In [26]:
n2[2:3]

array([2])

In [29]:
n2[-3]

2

In [31]:
n3 = np.array([[11,12,13,14],[15,16,17,18]])
print(n3)

[[11 12 13 14]
 [15 16 17 18]]


In [33]:
n3[0:,1:3]

array([[12, 13],
       [16, 17]])

In [44]:
n1[:2,:,:2]

array([[[111, 112],
        [114, 115]],

       [[211, 212],
        [214, 215]]])

In [49]:
n1.reshape(2,3,3)

array([[[111, 112, 113],
        [114, 115, 116],
        [211, 212, 213]],

       [[214, 215, 216],
        [311, 312, 313],
        [314, 315, 316]]])

In [53]:
np.arange(0,20,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [55]:
np.arange(-5,20,2)

array([-5, -3, -1,  1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

In [56]:
np.zeros([2,3,3])

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])